"""phase2 content hash reuse

Revision ID: 1faf50795c48
Revises: eccdfbf1bbfa
Create Date: 2026-08-25 19:18:56.134759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1faf50795c48'
down_revision: Union[str, Sequence[str], None] = 'eccdfbf1bbfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_batches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('reused_from', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_import_batches_content_hash'), ['content_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_batches_content_hash'))
        batch_op.drop_column('reused_from')
        batch_op.drop_column('content_hash')

    # ### end Alembic commands ###
