"""profile fields

Revision ID: daca5c16632c
Revises: 1faf50795c48
Create Date: 2026-08-25 23:24:51.179485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'daca5c16632c'
down_revision: Union[str, Sequence[str], None] = '1faf50795c48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_state', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('profile_name', sa.String(length=80), nullable=False, server_default='PLAYER ONE')
        )
        batch_op.add_column(
            sa.Column('profile_color', sa.String(length=7), nullable=False, server_default='#FFD93D')
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_state', schema=None) as batch_op:
        batch_op.drop_column('profile_color')
        batch_op.drop_column('profile_name')

    # ### end Alembic commands ###
