"""phase2 ai ingestion

Revision ID: eccdfbf1bbfa
Revises: 966eab3e9e4e
Create Date: 2026-08-25 16:55:35.362487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eccdfbf1bbfa'
down_revision: Union[str, Sequence[str], None] = '966eab3e9e4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=16), nullable=False),
    sa.Column('raw_source', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('interview_state', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_batches'))
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('confidence', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('import_batch_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_tasks_import_batch_id_import_batches'), 'import_batches', ['import_batch_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tasks_import_batch_id_import_batches'), type_='foreignkey')
        batch_op.drop_column('import_batch_id')
        batch_op.drop_column('confidence')
        batch_op.drop_column('priority_score')

    op.drop_table('import_batches')
    # ### end Alembic commands ###
